version: '2'
services:
    alumniproj-app:
        image: alumniproj
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://alumniproj-mysql:3306/alumniproj?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=alumniproj-elasticsearch:9300
        ports:
            - 8080:8080
    alumniproj-mysql:
        extends:
            file: mysql.yml
            service: alumniproj-mysql
    alumniproj-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: alumniproj-elasticsearch
